version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports: 
      - "3000:3000"
    volumes: 
      - ./app:/opt/web